---
- name: k8s demo service create
  hosts: all
  gather_facts: false
  connection: local
  vars:
    project_name: "project-test01"
  tasks:
    - name: Create a Service object from an inline definition
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: web
            namespace: "{{ project_name }}"
            labels:
              app: galaxy
              service: web
          spec:
            selector:
              app: galaxy
              service: web
            ports:
            - protocol: TCP
              targetPort: 8000
              name: port-8000-tcp
              port: 8000                                                                                                                                                                                                  
